import { Role } from "@prisma/client";

export const users = [
  {
    firstName: "Ravid",
    lastName: "Bizley",
    email: "rbizley0@51.la",
    password: "tUkfBNGz87",
    phoneNumber: "2226344168",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Helenelizabeth",
    lastName: "Blamire",
    email: "hblamire1@boston.com",
    password: "OH90uDFsKXYu",
    phoneNumber: "1759090109",
    isActive: true,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Elonore",
    lastName: "Ethersey",
    email: "eethersey2@printfriendly.com",
    password: "koz2P9q",
    phoneNumber: "6218772469",
    isActive: true,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Kendra",
    lastName: "Duncklee",
    email: "kduncklee3@comsenz.com",
    password: "rgmvvR1kHqA",
    phoneNumber: "4868923440",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Trefor",
    lastName: "McGlew",
    email: "tmcglew4@friendfeed.com",
    password: "2xlAglqr",
    phoneNumber: "5096145099",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Ignacio",
    lastName: "Aleavy",
    email: "ialeavy0@jalbum.net",
    password: "ZEBZOmAG4e",
    phoneNumber: "8666398233",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Gerhardine",
    lastName: "Corcoran",
    email: "gcorcoran1@go.com",
    password: "ZC23DT4ukzL",
    phoneNumber: "7932756823",
    isActive: true,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Mortie",
    lastName: "Blythin",
    email: "mblythin2@china.com.cn",
    password: "aQeaccHVIq",
    phoneNumber: "1209841699",
    isActive: false,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Gayel",
    lastName: "Emanueli",
    email: "gemanueli3@oracle.com",
    password: "uP2gUQZ",
    phoneNumber: "7478077894",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Lorie",
    lastName: "Kunneke",
    email: "lkunneke4@drupal.org",
    password: "mXoOQ2ms6vxL",
    phoneNumber: "4688091372",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Rosabella",
    lastName: "Peasnone",
    email: "rpeasnone0@howstuffworks.com",
    password: "rz72Rnv",
    phoneNumber: "2158445752",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Sonja",
    lastName: "Winchcomb",
    email: "swinchcomb1@forbes.com",
    password: "zpXCIJ",
    phoneNumber: "3296774084",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Diahann",
    lastName: "Duckitt",
    email: "dduckitt2@smugmug.com",
    password: "r6kzn7Lv",
    phoneNumber: "9784033913",
    isActive: false,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Paton",
    lastName: "Woollacott",
    email: "pwoollacott3@huffingtonpost.com",
    password: "3HnMkHS9yriK",
    phoneNumber: "3943709249",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Eddi",
    lastName: "Huie",
    email: "ehuie4@thetimes.co.uk",
    password: "5HA0CX",
    phoneNumber: "3785803628",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Sloan",
    lastName: "Clarridge",
    email: "sclarridge0@independent.co.uk",
    password: "nkP14a",
    phoneNumber: "6747427113",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Filmore",
    lastName: "Siemon",
    email: "fsiemon1@oracle.com",
    password: "23OsAGuZc",
    phoneNumber: "3404927664",
    isActive: true,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Kimberley",
    lastName: "Schuh",
    email: "kschuh2@plala.or.jp",
    password: "G872SJriv6ME",
    phoneNumber: "7151000668",
    isActive: true,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Edithe",
    lastName: "Franzelini",
    email: "efranzelini3@army.mil",
    password: "FSDWFDf",
    phoneNumber: "5065614446",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Tania",
    lastName: "Allaway",
    email: "tallaway4@simplemachines.org",
    password: "gKOwz3lee3",
    phoneNumber: "2933484478",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Guinevere",
    lastName: "Norcutt",
    email: "gnorcutt0@deviantart.com",
    password: "TxxBzBfsC",
    phoneNumber: "4941427323",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Gwendolen",
    lastName: "Sirkett",
    email: "gsirkett1@exblog.jp",
    password: "Cmrhs4Tru44G",
    phoneNumber: "2804308789",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Eberto",
    lastName: "Ife",
    email: "eife2@sphinn.com",
    password: "0LlpOOvDyfN",
    phoneNumber: "4309195889",
    isActive: true,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Sky",
    lastName: "Olivas",
    email: "solivas3@bing.com",
    password: "v7CjjbJyw3Z",
    phoneNumber: "9554830687",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Arielle",
    lastName: "Ricks",
    email: "aricks4@privacy.gov.au",
    password: "zQ5uDnT8",
    phoneNumber: "8669056522",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Kendra",
    lastName: "Robertot",
    email: "krobertot0@hhs.gov",
    password: "DfLVHRry9",
    phoneNumber: "3964218556",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Flossie",
    lastName: "Sarvar",
    email: "fsarvar1@hugedomains.com",
    password: "jAXs23B",
    phoneNumber: "9099705820",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Boyce",
    lastName: "Kinnach",
    email: "bkinnach2@linkedin.com",
    password: "lptE869j3iJr",
    phoneNumber: "7977038702",
    isActive: false,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Gilda",
    lastName: "Jedrzejewsky",
    email: "gjedrzejewsky3@oracle.com",
    password: "aCffAqjT6Yie",
    phoneNumber: "8312978608",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Daphne",
    lastName: "Govey",
    email: "dgovey4@census.gov",
    password: "nE5Qun",
    phoneNumber: "7124643156",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Joletta",
    lastName: "Ferrara",
    email: "jferrara0@xing.com",
    password: "iQwe6pEz",
    phoneNumber: "1303635573",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Greggory",
    lastName: "Stratford",
    email: "gstratford1@hubpages.com",
    password: "hNLhF0sPpg",
    phoneNumber: "7007809104",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Bentlee",
    lastName: "Simenot",
    email: "bsimenot2@cornell.edu",
    password: "9Sp5d6hoO",
    phoneNumber: "2368309116",
    isActive: false,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Carmelina",
    lastName: "Causnett",
    email: "ccausnett3@uol.com.br",
    password: "6XMNWF",
    phoneNumber: "4318667039",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Rubetta",
    lastName: "Krugmann",
    email: "rkrugmann4@xinhuanet.com",
    password: "3jrgWs",
    phoneNumber: "8289162752",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Lin",
    lastName: "Gauthorpp",
    email: "lgauthorpp0@tinyurl.com",
    password: "5ubu0A81q",
    phoneNumber: "2922161927",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Devonne",
    lastName: "Caroll",
    email: "dcaroll1@unc.edu",
    password: "UZWSyk4fC1B",
    phoneNumber: "2821266946",
    isActive: true,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Ardisj",
    lastName: "Learmond",
    email: "alearmond2@wordpress.org",
    password: "7pQ7m2",
    phoneNumber: "4088126934",
    isActive: true,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Kipp",
    lastName: "Braunroth",
    email: "kbraunroth3@reverbnation.com",
    password: "pPx9W5WLFfAK",
    phoneNumber: "3544517904",
    isActive: true,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Vincenty",
    lastName: "Wagen",
    email: "vwagen4@vkontakte.ru",
    password: "H9Nki3scS",
    phoneNumber: "7526509986",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Taite",
    lastName: "Boyle",
    email: "tboyle0@weibo.com",
    password: "KILoDnMB4",
    phoneNumber: "8293483255",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Lori",
    lastName: "Gallichan",
    email: "lgallichan1@cbc.ca",
    password: "fNWkNBwWv0Hs",
    phoneNumber: "7243524643",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Hamid",
    lastName: "Castellini",
    email: "hcastellini2@nationalgeographic.com",
    password: "MtCr6c",
    phoneNumber: "4503060169",
    isActive: false,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Ree",
    lastName: "Takos",
    email: "rtakos3@vistaprint.com",
    password: "vLrHojGke",
    phoneNumber: "6424246403",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Lexis",
    lastName: "Pinkett",
    email: "lpinkett4@si.edu",
    password: "NSopyU0A",
    phoneNumber: "4075858607",
    isActive: true,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Bryanty",
    lastName: "McNevin",
    email: "bmcnevin0@amazon.co.jp",
    password: "LG3FmJc5c2VF",
    phoneNumber: "3903704371",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
  {
    firstName: "Giselbert",
    lastName: "Blunden",
    email: "gblunden1@cargocollective.com",
    password: "k6oXjvy7xpY",
    phoneNumber: "7758823434",
    isActive: false,
    role: Role.ADMIN,
    auth: null,
  },
  {
    firstName: "Mathilde",
    lastName: "Keher",
    email: "mkeher2@rediff.com",
    password: "zHpOyzSzTfm",
    phoneNumber: "7822979884",
    isActive: true,
    role: Role.SUPERADMIN,
    auth: null,
  },
  {
    firstName: "Benjamin",
    lastName: "Lodovichi",
    email: "blodovichi3@privacy.gov.au",
    password: "xxo7Kyb",
    phoneNumber: "5457283883",
    isActive: false,
    role: undefined,
    auth: null,
  },
  {
    firstName: "Perry",
    lastName: "Lavens",
    email: "plavens4@icio.us",
    password: "Jn0p8k05XfD",
    phoneNumber: "6543560350",
    isActive: false,
    role: Role.USER,
    auth: null,
  },
];

export const organizations = [
  {
    name: "Yata",
    address: "3480 Annamark Plaza",
    city: "Las Vegas",
    state: "Nevada",
    zipCode: "89130",
    phoneNumber: "7022106424",
    isActive: false,
    users: [
      {
        firstName: "Ravid",
        lastName: "Bizley",
        email: "rbizley0@51.la",
        password: "tUkfBNGz87",
        phoneNumber: "2226344168",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Helenelizabeth",
        lastName: "Blamire",
        email: "hblamire1@boston.com",
        password: "OH90uDFsKXYu",
        phoneNumber: "1759090109",
        isActive: true,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Elonore",
        lastName: "Ethersey",
        email: "eethersey2@printfriendly.com",
        password: "koz2P9q",
        phoneNumber: "6218772469",
        isActive: true,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Kendra",
        lastName: "Duncklee",
        email: "kduncklee3@comsenz.com",
        password: "rgmvvR1kHqA",
        phoneNumber: "4868923440",
        isActive: false,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Trefor",
        lastName: "McGlew",
        email: "tmcglew4@friendfeed.com",
        password: "2xlAglqr",
        phoneNumber: "5096145099",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
    ],
  },
  {
    name: "Voonix",
    address: "66556 Roxbury Hill",
    city: "San Francisco",
    state: "California",
    zipCode: "94154",
    phoneNumber: "4156375794",
    isActive: false,
    users: [
      {
        firstName: "Ignacio",
        lastName: "Aleavy",
        email: "ialeavy0@jalbum.net",
        password: "ZEBZOmAG4e",
        phoneNumber: "8666398233",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Gerhardine",
        lastName: "Corcoran",
        email: "gcorcoran1@go.com",
        password: "ZC23DT4ukzL",
        phoneNumber: "7932756823",
        isActive: true,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Mortie",
        lastName: "Blythin",
        email: "mblythin2@china.com.cn",
        password: "aQeaccHVIq",
        phoneNumber: "1209841699",
        isActive: false,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Gayel",
        lastName: "Emanueli",
        email: "gemanueli3@oracle.com",
        password: "uP2gUQZ",
        phoneNumber: "7478077894",
        isActive: true,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Lorie",
        lastName: "Kunneke",
        email: "lkunneke4@drupal.org",
        password: "mXoOQ2ms6vxL",
        phoneNumber: "4688091372",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
    ],
  },
  {
    name: "Twitterbeat",
    address: "93882 Almo Place",
    city: "Minneapolis",
    state: "Minnesota",
    zipCode: "55446",
    phoneNumber: "9528061633",
    isActive: true,
    users: [
      {
        firstName: "Rosabella",
        lastName: "Peasnone",
        email: "rpeasnone0@howstuffworks.com",
        password: "rz72Rnv",
        phoneNumber: "2158445752",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Sonja",
        lastName: "Winchcomb",
        email: "swinchcomb1@forbes.com",
        password: "zpXCIJ",
        phoneNumber: "3296774084",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Diahann",
        lastName: "Duckitt",
        email: "dduckitt2@smugmug.com",
        password: "r6kzn7Lv",
        phoneNumber: "9784033913",
        isActive: false,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Paton",
        lastName: "Woollacott",
        email: "pwoollacott3@huffingtonpost.com",
        password: "3HnMkHS9yriK",
        phoneNumber: "3943709249",
        isActive: true,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Eddi",
        lastName: "Huie",
        email: "ehuie4@thetimes.co.uk",
        password: "5HA0CX",
        phoneNumber: "3785803628",
        isActive: false,
        role: undefined,
        auth: null,
      },
    ],
  },
  {
    name: "Yacero",
    address: "19 8th Point",
    city: "Tulsa",
    state: "Oklahoma",
    zipCode: "74170",
    phoneNumber: "9184322226",
    isActive: true,
    users: [
      {
        firstName: "Sloan",
        lastName: "Clarridge",
        email: "sclarridge0@independent.co.uk",
        password: "nkP14a",
        phoneNumber: "6747427113",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Filmore",
        lastName: "Siemon",
        email: "fsiemon1@oracle.com",
        password: "23OsAGuZc",
        phoneNumber: "3404927664",
        isActive: true,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Kimberley",
        lastName: "Schuh",
        email: "kschuh2@plala.or.jp",
        password: "G872SJriv6ME",
        phoneNumber: "7151000668",
        isActive: true,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Edithe",
        lastName: "Franzelini",
        email: "efranzelini3@army.mil",
        password: "FSDWFDf",
        phoneNumber: "5065614446",
        isActive: false,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Tania",
        lastName: "Allaway",
        email: "tallaway4@simplemachines.org",
        password: "gKOwz3lee3",
        phoneNumber: "2933484478",
        isActive: true,
        role: undefined,
        auth: null,
      },
    ],
  },
  {
    name: "Buzzster",
    address: "23470 Charing Cross Way",
    city: "Gainesville",
    state: "Georgia",
    zipCode: "30506",
    phoneNumber: "7707827037",
    isActive: false,
    users: [
      {
        firstName: "Guinevere",
        lastName: "Norcutt",
        email: "gnorcutt0@deviantart.com",
        password: "TxxBzBfsC",
        phoneNumber: "4941427323",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Gwendolen",
        lastName: "Sirkett",
        email: "gsirkett1@exblog.jp",
        password: "Cmrhs4Tru44G",
        phoneNumber: "2804308789",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Eberto",
        lastName: "Ife",
        email: "eife2@sphinn.com",
        password: "0LlpOOvDyfN",
        phoneNumber: "4309195889",
        isActive: true,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Sky",
        lastName: "Olivas",
        email: "solivas3@bing.com",
        password: "v7CjjbJyw3Z",
        phoneNumber: "9554830687",
        isActive: false,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Arielle",
        lastName: "Ricks",
        email: "aricks4@privacy.gov.au",
        password: "zQ5uDnT8",
        phoneNumber: "8669056522",
        isActive: true,
        role: undefined,
        auth: null,
      },
    ],
  },
  {
    name: "Camido",
    address: "7157 Crowley Parkway",
    city: "Yonkers",
    state: "New York",
    zipCode: "10705",
    phoneNumber: "9144386175",
    isActive: true,
    users: [
      {
        firstName: "Kendra",
        lastName: "Robertot",
        email: "krobertot0@hhs.gov",
        password: "DfLVHRry9",
        phoneNumber: "3964218556",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Flossie",
        lastName: "Sarvar",
        email: "fsarvar1@hugedomains.com",
        password: "jAXs23B",
        phoneNumber: "9099705820",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Boyce",
        lastName: "Kinnach",
        email: "bkinnach2@linkedin.com",
        password: "lptE869j3iJr",
        phoneNumber: "7977038702",
        isActive: false,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Gilda",
        lastName: "Jedrzejewsky",
        email: "gjedrzejewsky3@oracle.com",
        password: "aCffAqjT6Yie",
        phoneNumber: "8312978608",
        isActive: true,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Daphne",
        lastName: "Govey",
        email: "dgovey4@census.gov",
        password: "nE5Qun",
        phoneNumber: "7124643156",
        isActive: false,
        role: undefined,
        auth: null,
      },
    ],
  },
  {
    name: "Realcube",
    address: "08890 Arkansas Lane",
    city: "Anchorage",
    state: "Alaska",
    zipCode: "99517",
    phoneNumber: "9074092352",
    isActive: false,
    users: [
      {
        firstName: "Joletta",
        lastName: "Ferrara",
        email: "jferrara0@xing.com",
        password: "iQwe6pEz",
        phoneNumber: "1303635573",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Greggory",
        lastName: "Stratford",
        email: "gstratford1@hubpages.com",
        password: "hNLhF0sPpg",
        phoneNumber: "7007809104",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Bentlee",
        lastName: "Simenot",
        email: "bsimenot2@cornell.edu",
        password: "9Sp5d6hoO",
        phoneNumber: "2368309116",
        isActive: false,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Carmelina",
        lastName: "Causnett",
        email: "ccausnett3@uol.com.br",
        password: "6XMNWF",
        phoneNumber: "4318667039",
        isActive: true,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Rubetta",
        lastName: "Krugmann",
        email: "rkrugmann4@xinhuanet.com",
        password: "3jrgWs",
        phoneNumber: "8289162752",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
    ],
  },
  {
    name: "Talane",
    address: "7 Cardinal Trail",
    city: "Indianapolis",
    state: "Indiana",
    zipCode: "46231",
    phoneNumber: "3172314369",
    isActive: false,
    users: [
      {
        firstName: "Lin",
        lastName: "Gauthorpp",
        email: "lgauthorpp0@tinyurl.com",
        password: "5ubu0A81q",
        phoneNumber: "2922161927",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Devonne",
        lastName: "Caroll",
        email: "dcaroll1@unc.edu",
        password: "UZWSyk4fC1B",
        phoneNumber: "2821266946",
        isActive: true,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Ardisj",
        lastName: "Learmond",
        email: "alearmond2@wordpress.org",
        password: "7pQ7m2",
        phoneNumber: "4088126934",
        isActive: true,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Kipp",
        lastName: "Braunroth",
        email: "kbraunroth3@reverbnation.com",
        password: "pPx9W5WLFfAK",
        phoneNumber: "3544517904",
        isActive: true,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Vincenty",
        lastName: "Wagen",
        email: "vwagen4@vkontakte.ru",
        password: "H9Nki3scS",
        phoneNumber: "7526509986",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
    ],
  },
  {
    name: "Thoughtblab",
    address: "057 Corben Center",
    city: "Atlanta",
    state: "Georgia",
    zipCode: "30343",
    phoneNumber: "4044372861",
    isActive: false,
    users: [
      {
        firstName: "Taite",
        lastName: "Boyle",
        email: "tboyle0@weibo.com",
        password: "KILoDnMB4",
        phoneNumber: "8293483255",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Lori",
        lastName: "Gallichan",
        email: "lgallichan1@cbc.ca",
        password: "fNWkNBwWv0Hs",
        phoneNumber: "7243524643",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Hamid",
        lastName: "Castellini",
        email: "hcastellini2@nationalgeographic.com",
        password: "MtCr6c",
        phoneNumber: "4503060169",
        isActive: false,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Ree",
        lastName: "Takos",
        email: "rtakos3@vistaprint.com",
        password: "vLrHojGke",
        phoneNumber: "6424246403",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Lexis",
        lastName: "Pinkett",
        email: "lpinkett4@si.edu",
        password: "NSopyU0A",
        phoneNumber: "4075858607",
        isActive: true,
        role: Role.USER,
        auth: null,
      },
    ],
  },
  {
    name: "Skyba",
    address: "4686 Graedel Road",
    city: "Pasadena",
    state: "California",
    zipCode: "91117",
    phoneNumber: "6266820582",
    isActive: true,
    users: [
      {
        firstName: "Bryanty",
        lastName: "McNevin",
        email: "bmcnevin0@amazon.co.jp",
        password: "LG3FmJc5c2VF",
        phoneNumber: "3903704371",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
      {
        firstName: "Giselbert",
        lastName: "Blunden",
        email: "gblunden1@cargocollective.com",
        password: "k6oXjvy7xpY",
        phoneNumber: "7758823434",
        isActive: false,
        role: Role.ADMIN,
        auth: null,
      },
      {
        firstName: "Mathilde",
        lastName: "Keher",
        email: "mkeher2@rediff.com",
        password: "zHpOyzSzTfm",
        phoneNumber: "7822979884",
        isActive: true,
        role: Role.SUPERADMIN,
        auth: null,
      },
      {
        firstName: "Benjamin",
        lastName: "Lodovichi",
        email: "blodovichi3@privacy.gov.au",
        password: "xxo7Kyb",
        phoneNumber: "5457283883",
        isActive: false,
        role: undefined,
        auth: null,
      },
      {
        firstName: "Perry",
        lastName: "Lavens",
        email: "plavens4@icio.us",
        password: "Jn0p8k05XfD",
        phoneNumber: "6543560350",
        isActive: false,
        role: Role.USER,
        auth: null,
      },
    ],
  },
];
